apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: qamelo-system
  labels:
    app.kubernetes.io/name: qamelo-connectivity
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: qamelo-connectivity
    app.kubernetes.io/instance: {{ .Release.Name }}
