{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: qamelo-system
  labels:
    app.kubernetes.io/name: qamelo-connectivity
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
